export interface Province {
  id: number;
  name: string;
}

export interface Canton {
  id: number;
  name: string;
  province_id: number;
}

export interface District {
  id: number;
  name: string;
  canton_id: number;
}

export const provinces: Province[] = [
  { id: 1, name: "San José" },
  { id: 2, name: "Alajuela" },
  { id: 3, name: "Cartago" },
  { id: 4, name: "Heredia" },
  { id: 5, name: "Guanacaste" },
  { id: 6, name: "Puntarenas" },
  { id: 7, name: "Limón" },
];

export const cantons: Canton[] = [
  // San José (1)
  { id: 1, name: "San José", province_id: 1 },
  { id: 2, name: "Escazú", province_id: 1 },
  { id: 3, name: "Desamparados", province_id: 1 },
  { id: 4, name: "Puriscal", province_id: 1 },
  { id: 5, name: "Tarrazú", province_id: 1 },
  { id: 6, name: "Aserrí", province_id: 1 },
  { id: 7, name: "Mora", province_id: 1 },
  { id: 8, name: "Goicoechea", province_id: 1 },
  { id: 9, name: "Santa Ana", province_id: 1 },
  { id: 10, name: "Alajuelita", province_id: 1 },
  { id: 11, name: "Vásquez de Coronado", province_id: 1 },
  { id: 12, name: "Acosta", province_id: 1 },
  { id: 13, name: "Tibás", province_id: 1 },
  { id: 14, name: "Moravia", province_id: 1 },
  { id: 15, name: "Montes de Oca", province_id: 1 },
  { id: 16, name: "Turrubares", province_id: 1 },
  { id: 17, name: "Dota", province_id: 1 },
  { id: 18, name: "Curridabat", province_id: 1 },
  { id: 19, name: "Pérez Zeledón", province_id: 1 },
  { id: 20, name: "León Cortés", province_id: 1 },
  // Alajuela (2)
  { id: 21, name: "Alajuela", province_id: 2 },
  { id: 22, name: "San Ramón", province_id: 2 },
  { id: 23, name: "Grecia", province_id: 2 },
  { id: 24, name: "San Mateo", province_id: 2 },
  { id: 25, name: "Atenas", province_id: 2 },
  { id: 26, name: "Naranjo", province_id: 2 },
  { id: 27, name: "Palmares", province_id: 2 },
  { id: 28, name: "Poás", province_id: 2 },
  { id: 29, name: "Orotina", province_id: 2 },
  { id: 30, name: "San Carlos", province_id: 2 },
  { id: 31, name: "Zarcero", province_id: 2 },
  { id: 32, name: "Sarchí", province_id: 2 },
  { id: 33, name: "Upala", province_id: 2 },
  { id: 34, name: "Los Chiles", province_id: 2 },
  { id: 35, name: "Guatuso", province_id: 2 },
  { id: 36, name: "Río Cuarto", province_id: 2 },
  // Cartago (3)
  { id: 37, name: "Cartago", province_id: 3 },
  { id: 38, name: "Paraíso", province_id: 3 },
  { id: 39, name: "La Unión", province_id: 3 },
  { id: 40, name: "Jiménez", province_id: 3 },
  { id: 41, name: "Turrialba", province_id: 3 },
  { id: 42, name: "Alvarado", province_id: 3 },
  { id: 43, name: "Oreamuno", province_id: 3 },
  { id: 44, name: "El Guarco", province_id: 3 },
  // Heredia (4)
  { id: 45, name: "Heredia", province_id: 4 },
  { id: 46, name: "Barva", province_id: 4 },
  { id: 47, name: "Santo Domingo", province_id: 4 },
  { id: 48, name: "Santa Bárbara", province_id: 4 },
  { id: 49, name: "San Rafael", province_id: 4 },
  { id: 50, name: "San Isidro", province_id: 4 },
  { id: 51, name: "Belén", province_id: 4 },
  { id: 52, name: "Flores", province_id: 4 },
  { id: 53, name: "San Pablo", province_id: 4 },
  { id: 54, name: "Sarapiquí", province_id: 4 },
  // Guanacaste (5)
  { id: 55, name: "Liberia", province_id: 5 },
  { id: 56, name: "Nicoya", province_id: 5 },
  { id: 57, name: "Santa Cruz", province_id: 5 },
  { id: 58, name: "Bagaces", province_id: 5 },
  { id: 59, name: "Carrillo", province_id: 5 },
  { id: 60, name: "Cañas", province_id: 5 },
  { id: 61, name: "Abangares", province_id: 5 },
  { id: 62, name: "Tilarán", province_id: 5 },
  { id: 63, name: "Nandayure", province_id: 5 },
  { id: 64, name: "La Cruz", province_id: 5 },
  { id: 65, name: "Hojancha", province_id: 5 },
  // Puntarenas (6)
  { id: 66, name: "Puntarenas", province_id: 6 },
  { id: 67, name: "Esparza", province_id: 6 },
  { id: 68, name: "Buenos Aires", province_id: 6 },
  { id: 69, name: "Montes de Oro", province_id: 6 },
  { id: 70, name: "Osa", province_id: 6 },
  { id: 71, name: "Quepos", province_id: 6 },
  { id: 72, name: "Golfito", province_id: 6 },
  { id: 73, name: "Coto Brus", province_id: 6 },
  { id: 74, name: "Parrita", province_id: 6 },
  { id: 75, name: "Corredores", province_id: 6 },
  { id: 76, name: "Garabito", province_id: 6 },
  // Limón (7)
  { id: 77, name: "Limón", province_id: 7 },
  { id: 78, name: "Pococí", province_id: 7 },
  { id: 79, name: "Siquirres", province_id: 7 },
  { id: 80, name: "Talamanca", province_id: 7 },
  { id: 81, name: "Matina", province_id: 7 },
  { id: 82, name: "Guácimo", province_id: 7 },
];

export const districts: District[] = [
  // San José (1)
  { id: 1, name: "Carmen", canton_id: 1 },
  { id: 2, name: "Merced", canton_id: 1 },
  { id: 3, name: "Hospital", canton_id: 1 },
  { id: 4, name: "Catedral", canton_id: 1 },
  { id: 5, name: "Zapote", canton_id: 1 },
  { id: 6, name: "San Francisco de Dos Ríos", canton_id: 1 },
  { id: 7, name: "Uruca", canton_id: 1 },
  { id: 8, name: "Mata Redonda", canton_id: 1 },
  { id: 9, name: "Pavas", canton_id: 1 },
  { id: 10, name: "Hatillo", canton_id: 1 },
  { id: 11, name: "San Sebastián", canton_id: 1 },
  // Escazú (2)
  { id: 12, name: "Escazú", canton_id: 2 },
  { id: 13, name: "San Antonio", canton_id: 2 },
  { id: 14, name: "San Rafael", canton_id: 2 },
  // Desamparados (3)
  { id: 15, name: "Desamparados", canton_id: 3 },
  { id: 16, name: "San Miguel", canton_id: 3 },
  { id: 17, name: "San Juan de Dios", canton_id: 3 },
  { id: 18, name: "San Rafael Arriba", canton_id: 3 },
  { id: 19, name: "San Antonio", canton_id: 3 },
  { id: 20, name: "Frailes", canton_id: 3 },
  { id: 21, name: "Patarrá", canton_id: 3 },
  { id: 22, name: "San Cristóbal", canton_id: 3 },
  { id: 23, name: "Rosario", canton_id: 3 },
  { id: 24, name: "Damas", canton_id: 3 },
  { id: 25, name: "San Rafael Abajo", canton_id: 3 },
  { id: 26, name: "Gravilias", canton_id: 3 },
  { id: 27, name: "Los Guido", canton_id: 3 },
  // Puriscal (4)
  { id: 28, name: "Santiago", canton_id: 4 },
  { id: 29, name: "Mercedes Sur", canton_id: 4 },
  { id: 30, name: "Barbacoas", canton_id: 4 },
  { id: 31, name: "Grifo Alto", canton_id: 4 },
  { id: 32, name: "San Rafael", canton_id: 4 },
  { id: 33, name: "Candelarita", canton_id: 4 },
  { id: 34, name: "Desamparaditos", canton_id: 4 },
  { id: 35, name: "San Antonio", canton_id: 4 },
  { id: 36, name: "Chiquichá", canton_id: 4 },
  { id: 37, name: "Bajo Legua", canton_id: 4 },
  { id: 38, name: "Merceditas", canton_id: 4 },
  // Tarrazú (5)
  { id: 39, name: "San Marcos", canton_id: 5 },
  { id: 40, name: "San Lorenzo", canton_id: 5 },
  { id: 41, name: "San Carlos", canton_id: 5 },
  // Aserrí (6)
  { id: 42, name: "Aserrí", canton_id: 6 },
  { id: 43, name: "Tarbaca", canton_id: 6 },
  { id: 44, name: "Vuelta de Jorco", canton_id: 6 },
  { id: 45, name: "San Gabriel", canton_id: 6 },
  { id: 46, name: "La Legua", canton_id: 6 },
  { id: 47, name: "Monterrey", canton_id: 6 },
  { id: 48, name: "Salitrillos", canton_id: 6 },
  // Mora (7)
  { id: 49, name: "Colón", canton_id: 7 },
  { id: 50, name: "Guayabo", canton_id: 7 },
  { id: 51, name: "Tabarcia", canton_id: 7 },
  { id: 52, name: "Piedras Negras", canton_id: 7 },
  { id: 53, name: "Picagres", canton_id: 7 },
  { id: 54, name: "Jaris", canton_id: 7 },
  { id: 55, name: "Quitirrisí", canton_id: 7 },
  // Goicoechea (8)
  { id: 56, name: "Guadalupe", canton_id: 8 },
  { id: 57, name: "San Francisco", canton_id: 8 },
  { id: 58, name: "Calle Blancos", canton_id: 8 },
  { id: 59, name: "Mata de Plátano", canton_id: 8 },
  { id: 60, name: "Ipís", canton_id: 8 },
  { id: 61, name: "Rancho Redondo", canton_id: 8 },
  { id: 62, name: "Purral", canton_id: 8 },
  // Santa Ana (9)
  { id: 63, name: "Santa Ana", canton_id: 9 },
  { id: 64, name: "Salitral", canton_id: 9 },
  { id: 65, name: "Pozos", canton_id: 9 },
  { id: 66, name: "Uruca", canton_id: 9 },
  { id: 67, name: "Piedades", canton_id: 9 },
  { id: 68, name: "Brasil", canton_id: 9 },
  // Alajuelita (10)
  { id: 69, name: "Alajuelita", canton_id: 10 },
  { id: 70, name: "San Josecito", canton_id: 10 },
  { id: 71, name: "San Antonio", canton_id: 10 },
  { id: 72, name: "Concepción", canton_id: 10 },
  { id: 73, name: "San Felipe", canton_id: 10 },
  // Vásquez de Coronado (11)
  { id: 74, name: "San Isidro", canton_id: 11 },
  { id: 75, name: "San Rafael", canton_id: 11 },
  { id: 76, name: "Dulce Nombre de Jesús", canton_id: 11 },
  { id: 77, name: "Patalillo", canton_id: 11 },
  { id: 78, name: "Cascajal", canton_id: 11 },
  // Acosta (12)
  { id: 79, name: "San Ignacio", canton_id: 12 },
  { id: 80, name: "Guaitil", canton_id: 12 },
  { id: 81, name: "Palmichal", canton_id: 12 },
  { id: 82, name: "Cangrejal", canton_id: 12 },
  { id: 83, name: "Sabanillas", canton_id: 12 },
  // Tibás (13)
  { id: 84, name: "San Juan", canton_id: 13 },
  { id: 85, name: "Cinco Esquinas", canton_id: 13 },
  { id: 86, name: "Anselmo Llorente", canton_id: 13 },
  { id: 87, name: "León XIII", canton_id: 13 },
  { id: 88, name: "Colima", canton_id: 13 },
  // Moravia (14)
  { id: 89, name: "San Vicente", canton_id: 14 },
  { id: 90, name: "San Jerónimo", canton_id: 14 },
  { id: 91, name: "La Trinidad", canton_id: 14 },
  // Montes de Oca (15)
  { id: 92, name: "San Pedro", canton_id: 15 },
  { id: 93, name: "Sabanilla", canton_id: 15 },
  { id: 94, name: "Mercedes", canton_id: 15 },
  { id: 95, name: "San Rafael", canton_id: 15 },
  // Turrubares (16)
  { id: 96, name: "San Pablo", canton_id: 16 },
  { id: 97, name: "San Pedro", canton_id: 16 },
  { id: 98, name: "San Juan de Mata", canton_id: 16 },
  { id: 99, name: "San Luis", canton_id: 16 },
  { id: 100, name: "Carara", canton_id: 16 },
  // Dota (17)
  { id: 101, name: "Santa María", canton_id: 17 },
  { id: 102, name: "Jardín", canton_id: 17 },
  { id: 103, name: "Copey", canton_id: 17 },
  // Curridabat (18)
  { id: 104, name: "Curridabat", canton_id: 18 },
  { id: 105, name: "Granadilla", canton_id: 18 },
  { id: 106, name: "Sánchez", canton_id: 18 },
  { id: 107, name: "Tirrases", canton_id: 18 },
  // Pérez Zeledón (19)
  { id: 108, name: "San Isidro de El General", canton_id: 19 },
  { id: 109, name: "El General", canton_id: 19 },
  { id: 110, name: "Daniel Flores", canton_id: 19 },
  { id: 111, name: "Rivas", canton_id: 19 },
  { id: 112, name: "San Pedro", canton_id: 19 },
  { id: 113, name: "Platanares", canton_id: 19 },
  { id: 114, name: "Pejibaye", canton_id: 19 },
  { id: 115, name: "Cajón", canton_id: 19 },
  { id: 116, name: "Barú", canton_id: 19 },
  { id: 117, name: "Río Nuevo", canton_id: 19 },
  { id: 118, name: "Páramo", canton_id: 19 },
  { id: 119, name: "La Amistad", canton_id: 19 },
  // León Cortés (20)
  { id: 120, name: "San Pablo", canton_id: 20 },
  { id: 121, name: "San Andrés", canton_id: 20 },
  { id: 122, name: "Llano Bonito", canton_id: 20 },
  { id: 123, name: "San Isidro", canton_id: 20 },
  { id: 124, name: "Santa Cruz", canton_id: 20 },
  { id: 125, name: "San Antonio", canton_id: 20 },
  // Alajuela (21)
  { id: 126, name: "Alajuela", canton_id: 21 },
  { id: 127, name: "San José", canton_id: 21 },
  { id: 128, name: "Carrizal", canton_id: 21 },
  { id: 129, name: "San Antonio", canton_id: 21 },
  { id: 130, name: "Guácimo", canton_id: 21 },
  { id: 131, name: "San Isidro", canton_id: 21 },
  { id: 132, name: "Sabanilla", canton_id: 21 },
  { id: 133, name: "San Rafael", canton_id: 21 },
  { id: 134, name: "Río Segundo", canton_id: 21 },
  { id: 135, name: "Desamparados", canton_id: 21 },
  { id: 136, name: "Turrúcares", canton_id: 21 },
  { id: 137, name: "Tambor", canton_id: 21 },
  { id: 138, name: "Garita", canton_id: 21 },
  { id: 139, name: "Sarapiquí", canton_id: 21 },
  // San Ramón (22)
  { id: 140, name: "San Ramón", canton_id: 22 },
  { id: 141, name: "Santiago", canton_id: 22 },
  { id: 142, name: "San Juan", canton_id: 22 },
  { id: 143, name: "Piedades Norte", canton_id: 22 },
  { id: 144, name: "Piedades Sur", canton_id: 22 },
  { id: 145, name: "San Rafael", canton_id: 22 },
  { id: 146, name: "San Isidro", canton_id: 22 },
  { id: 147, name: "Ángeles", canton_id: 22 },
  { id: 148, name: "Alfaro", canton_id: 22 },
  { id: 149, name: "Volio", canton_id: 22 },
  { id: 150, name: "Concepción", canton_id: 22 },
  { id: 151, name: "Zapotal", canton_id: 22 },
  { id: 152, name: "Peñas Blancas", canton_id: 22 },
  { id: 153, name: "San Lorenzo", canton_id: 22 },
  // Grecia (23)
  { id: 154, name: "Grecia", canton_id: 23 },
  { id: 155, name: "San Isidro", canton_id: 23 },
  { id: 156, name: "San José", canton_id: 23 },
  { id: 157, name: "San Roque", canton_id: 23 },
  { id: 158, name: "Tacares", canton_id: 23 },
  { id: 159, name: "Río Cuarto", canton_id: 23 },
  { id: 160, name: "Puente de Piedra", canton_id: 23 },
  { id: 161, name: "Bolívar", canton_id: 23 },
  // San Mateo (24)
  { id: 162, name: "San Mateo", canton_id: 24 },
  { id: 163, name: "Desmonte", canton_id: 24 },
  { id: 164, name: "Jesús María", canton_id: 24 },
  { id: 165, name: "Labrador", canton_id: 24 },
  // Atenas (25)
  { id: 166, name: "Atenas", canton_id: 25 },
  { id: 167, name: "Jesús", canton_id: 25 },
  { id: 168, name: "Mercedes", canton_id: 25 },
  { id: 169, name: "San Isidro", canton_id: 25 },
  { id: 170, name: "Concepción", canton_id: 25 },
  { id: 171, name: "San José", canton_id: 25 },
  { id: 172, name: "Santa Eulalia", canton_id: 25 },
  { id: 173, name: "Escobal", canton_id: 25 },
  // Naranjo (26)
  { id: 174, name: "Naranjo", canton_id: 26 },
  { id: 175, name: "San Miguel", canton_id: 26 },
  { id: 176, name: "San José", canton_id: 26 },
  { id: 177, name: "Cirrí Sur", canton_id: 26 },
  { id: 178, name: "San Jerónimo", canton_id: 26 },
  { id: 179, name: "San Juan", canton_id: 26 },
  { id: 180, name: "El Rosario", canton_id: 26 },
  { id: 181, name: "Palmitos", canton_id: 26 },
  // Palmares (27)
  { id: 182, name: "Palmares", canton_id: 27 },
  { id: 183, name: "Zaragoza", canton_id: 27 },
  { id: 184, name: "Buenos Aires", canton_id: 27 },
  { id: 185, name: "Santiago", canton_id: 27 },
  { id: 186, name: "Candelaria", canton_id: 27 },
  { id: 187, name: "Esquipulas", canton_id: 27 },
  { id: 188, name: "La Granja", canton_id: 27 },
  // Poás (28)
  { id: 189, name: "San Pedro", canton_id: 28 },
  { id: 190, name: "San Juan", canton_id: 28 },
  { id: 191, name: "San Rafael", canton_id: 28 },
  { id: 192, name: "Carrillos", canton_id: 28 },
  { id: 193, name: "Sabana Redonda", canton_id: 28 },
  // Orotina (29)
  { id: 194, name: "Orotina", canton_id: 29 },
  { id: 195, name: "El Mastate", canton_id: 29 },
  { id: 196, name: "Hacienda Vieja", canton_id: 29 },
  { id: 197, name: "Coyolar", canton_id: 29 },
  { id: 198, name: "La Ceiba", canton_id: 29 },
  // San Carlos (30)
  { id: 199, name: "Quesada", canton_id: 30 },
  { id: 200, name: "Florencia", canton_id: 30 },
  { id: 201, name: "Buenavista", canton_id: 30 },
  { id: 202, name: "Aguas Zarcas", canton_id: 30 },
  { id: 203, name: "Venecia", canton_id: 30 },
  { id: 204, name: "Pital", canton_id: 30 },
  { id: 205, name: "La Fortuna", canton_id: 30 },
  { id: 206, name: "La Tigra", canton_id: 30 },
  { id: 207, name: "La Palmera", canton_id: 30 },
  { id: 208, name: "Venado", canton_id: 30 },
  { id: 209, name: "Cutris", canton_id: 30 },
  { id: 210, name: "Monterrey", canton_id: 30 },
  { id: 211, name: "Pocosol", canton_id: 30 },
  // Zarcero (31)
  { id: 212, name: "Zarcero", canton_id: 31 },
  { id: 213, name: "Laguna", canton_id: 31 },
  { id: 214, name: "Tapesco", canton_id: 31 },
  { id: 215, name: "Guadalupe", canton_id: 31 },
  { id: 216, name: "Palmira", canton_id: 31 },
  { id: 217, name: "Zapote", canton_id: 31 },
  { id: 218, name: "Brisas", canton_id: 31 },
  // Sarchí (32)
  { id: 219, name: "Sarchí Norte", canton_id: 32 },
  { id: 220, name: "Sarchí Sur", canton_id: 32 },
  { id: 221, name: "Toro Amarillo", canton_id: 32 },
  { id: 222, name: "San Pedro", canton_id: 32 },
  { id: 223, name: "Rodríguez", canton_id: 32 },
  // Upala (33)
  { id: 224, name: "Upala", canton_id: 33 },
  { id: 225, name: "Aguas Claras", canton_id: 33 },
  { id: 226, name: "San José o Pizote", canton_id: 33 },
  { id: 227, name: "Bijagua", canton_id: 33 },
  { id: 228, name: "Delicias", canton_id: 33 },
  { id: 229, name: "Dos Ríos", canton_id: 33 },
  { id: 230, name: "Yolillal", canton_id: 33 },
  { id: 231, name: "Canalete", canton_id: 33 },
  // Los Chiles (34)
  { id: 232, name: "Los Chiles", canton_id: 34 },
  { id: 233, name: "Caño Negro", canton_id: 34 },
  { id: 234, name: "El Amparo", canton_id: 34 },
  { id: 235, name: "San Jorge", canton_id: 34 },
  // Guatuso (35)
  { id: 236, name: "San Rafael", canton_id: 35 },
  { id: 237, name: "Buenavista", canton_id: 35 },
  { id: 238, name: "Cote", canton_id: 35 },
  { id: 239, name: "Katira", canton_id: 35 },
  // Río Cuarto (36)
  { id: 240, name: "Río Cuarto", canton_id: 36 },
  { id: 241, name: "Santa Rita", canton_id: 36 },
  { id: 242, name: "Santa Isabel", canton_id: 36 },
  // Cartago (37)
  { id: 243, name: "Oriental", canton_id: 37 },
  { id: 244, name: "Occidental", canton_id: 37 },
  { id: 245, name: "Carmen", canton_id: 37 },
  { id: 246, name: "San Nicolás", canton_id: 37 },
  { id: 247, name: "Aguacaliente", canton_id: 37 },
  { id: 248, name: "Guadalupe", canton_id: 37 },
  { id: 249, name: "Corralillo", canton_id: 37 },
  { id: 250, name: "Tierra Blanca", canton_id: 37 },
  { id: 251, name: "Dulce Nombre", canton_id: 37 },
  { id: 252, name: "Llano Grande", canton_id: 37 },
  { id: 253, name: "Quebradilla", canton_id: 37 },
  // Paraíso (38)
  { id: 254, name: "Paraíso", canton_id: 38 },
  { id: 255, name: "Santiago", canton_id: 38 },
  { id: 256, name: "Orosi", canton_id: 38 },
  { id: 257, name: "Cachí", canton_id: 38 },
  { id: 258, name: "Llanos de Santa Lucía", canton_id: 38 },
  // La Unión (39)
  { id: 259, name: "Tres Ríos", canton_id: 39 },
  { id: 260, name: "San Diego", canton_id: 39 },
  { id: 261, name: "San Juan", canton_id: 39 },
  { id: 262, name: "San Rafael", canton_id: 39 },
  { id: 263, name: "Concepción", canton_id: 39 },
  { id: 264, name: "Dulce Nombre", canton_id: 39 },
  { id: 265, name: "San Ramón", canton_id: 39 },
  { id: 266, name: "Río Azul", canton_id: 39 },
  // Jiménez (40)
  { id: 267, name: "Juan Viñas", canton_id: 40 },
  { id: 268, name: "Tucurrique", canton_id: 40 },
  { id: 269, name: "Pejibaye", canton_id: 40 },
  // Turrialba (41)
  { id: 270, name: "Turrialba", canton_id: 41 },
  { id: 271, name: "La Suiza", canton_id: 41 },
  { id: 272, name: "Peralta", canton_id: 41 },
  { id: 273, name: "Santa Cruz", canton_id: 41 },
  { id: 274, name: "Santa Teresita", canton_id: 41 },
  { id: 275, name: "Pavones", canton_id: 41 },
  { id: 276, name: "Tuis", canton_id: 41 },
  { id: 277, name: "Tayutic", canton_id: 41 },
  { id: 278, name: "Santa Rosa", canton_id: 41 },
  { id: 279, name: "Tres Equis", canton_id: 41 },
  { id: 280, name: "La Isabel", canton_id: 41 },
  { id: 281, name: "Chirripó", canton_id: 41 },
  // Alvarado (42)
  { id: 282, name: "Pacayas", canton_id: 42 },
  { id: 283, name: "Cervantes", canton_id: 42 },
  { id: 284, name: "Capellades", canton_id: 42 },
  // Oreamuno (43)
  { id: 285, name: "San Rafael", canton_id: 43 },
  { id: 286, name: "Cot", canton_id: 43 },
  { id: 287, name: "Potrero Cerrado", canton_id: 43 },
  { id: 288, name: "Cipreses", canton_id: 43 },
  { id: 289, name: "Santa Rosa", canton_id: 43 },
  // El Guarco (44)
  { id: 290, name: "El Tejar", canton_id: 44 },
  { id: 291, name: "San Isidro", canton_id: 44 },
  { id: 292, name: "Tobosi", canton_id: 44 },
  { id: 293, name: "Patio de Agua", canton_id: 44 },
  // Heredia (45)
  { id: 294, name: "Heredia", canton_id: 45 },
  { id: 295, name: "Mercedes", canton_id: 45 },
  { id: 296, name: "San Francisco", canton_id: 45 },
  { id: 297, name: "Ulloa", canton_id: 45 },
  { id: 298, name: "Varablanca", canton_id: 45 },
  // Barva (46)
  { id: 299, name: "Barva", canton_id: 46 },
  { id: 300, name: "San Pedro", canton_id: 46 },
  { id: 301, name: "San Pablo", canton_id: 46 },
  { id: 302, name: "San Roque", canton_id: 46 },
  { id: 303, name: "Santa Lucía", canton_id: 46 },
  { id: 304, name: "San José de la Montaña", canton_id: 46 },
  // Santo Domingo (47)
  { id: 305, name: "Santo Domingo", canton_id: 47 },
  { id: 306, name: "San Vicente", canton_id: 47 },
  { id: 307, name: "San Miguel", canton_id: 47 },
  { id: 308, name: "Paracito", canton_id: 47 },
  { id: 309, name: "Santo Tomás", canton_id: 47 },
  { id: 310, name: "Santa Rosa", canton_id: 47 },
  { id: 311, name: "Tures", canton_id: 47 },
  { id: 312, name: "Pará", canton_id: 47 },
  // Santa Bárbara (48)
  { id: 313, name: "Santa Bárbara", canton_id: 48 },
  { id: 314, name: "San Pedro", canton_id: 48 },
  { id: 315, name: "San Juan", canton_id: 48 },
  { id: 316, name: "Jesús", canton_id: 48 },
  { id: 317, name: "Santo Domingo", canton_id: 48 },
  { id: 318, name: "Puraba", canton_id: 48 },
  // San Rafael (49)
  { id: 319, name: "San Rafael", canton_id: 49 },
  { id: 320, name: "San Josecito", canton_id: 49 },
  { id: 321, name: "Santiago", canton_id: 49 },
  { id: 322, name: "Ángeles", canton_id: 49 },
  { id: 323, name: "Concepción", canton_id: 49 },
  // San Isidro (50)
  { id: 324, name: "San Isidro", canton_id: 50 },
  { id: 325, name: "San José", canton_id: 50 },
  { id: 326, name: "Concepción", canton_id: 50 },
  { id: 327, name: "San Francisco", canton_id: 50 },
  // Belén (51)
  { id: 328, name: "San Antonio", canton_id: 51 },
  { id: 329, name: "La Ribera", canton_id: 51 },
  { id: 330, name: "La Asunción", canton_id: 51 },
  // Flores (52)
  { id: 331, name: "San Joaquín", canton_id: 52 },
  { id: 332, name: "Barrantes", canton_id: 52 },
  { id: 333, name: "Llorente", canton_id: 52 },
  // San Pablo (53)
  { id: 334, name: "San Pablo", canton_id: 53 },
  { id: 335, name: "Rincón de Sabanilla", canton_id: 53 },
  // Sarapiquí (54)
  { id: 336, name: "Puerto Viejo", canton_id: 54 },
  { id: 337, name: "La Virgen", canton_id: 54 },
  { id: 338, name: "Las Horquetas", canton_id: 54 },
  { id: 339, name: "Llanuras del Gaspar", canton_id: 54 },
  { id: 340, name: "Cureña", canton_id: 54 },
  // Liberia (55)
  { id: 341, name: "Liberia", canton_id: 55 },
  { id: 342, name: "Cañas Dulces", canton_id: 55 },
  { id: 343, name: "Mayorga", canton_id: 55 },
  { id: 344, name: "Nacascolo", canton_id: 55 },
  { id: 345, name: "Curubandé", canton_id: 55 },
  // Nicoya (56)
  { id: 346, name: "Nicoya", canton_id: 56 },
  { id: 347, name: "Mansión", canton_id: 56 },
  { id: 348, name: "San Antonio", canton_id: 56 },
  { id: 349, name: "Quebrada Honda", canton_id: 56 },
  { id: 350, name: "Sámara", canton_id: 56 },
  { id: 351, name: "Nosara", canton_id: 56 },
  { id: 352, name: "Belén de Nosarita", canton_id: 56 },
  // Santa Cruz (57)
  { id: 353, name: "Santa Cruz", canton_id: 57 },
  { id: 354, name: "Bolsón", canton_id: 57 },
  { id: 355, name: "Veintisiete de Abril", canton_id: 57 },
  { id: 356, name: "Tempate", canton_id: 57 },
  { id: 357, name: "Cartagena", canton_id: 57 },
  { id: 358, name: "Cuajiniquil", canton_id: 57 },
  { id: 359, name: "Diriá", canton_id: 57 },
  { id: 360, name: "Cabo Velas", canton_id: 57 },
  { id: 361, name: "Tamarindo", canton_id: 57 },
  // Bagaces (58)
  { id: 362, name: "Bagaces", canton_id: 58 },
  { id: 363, name: "La Fortuna", canton_id: 58 },
  { id: 364, name: "Maravilla", canton_id: 58 },
  { id: 365, name: "Mogote", canton_id: 58 },
  { id: 366, name: "Río Naranjo", canton_id: 58 },
  // Carrillo (59)
  { id: 367, name: "Filadelfia", canton_id: 59 },
  { id: 368, name: "Palmira", canton_id: 59 },
  { id: 369, name: "Sardinal", canton_id: 59 },
  { id: 370, name: "Belén", canton_id: 59 },
  // Cañas (60)
  { id: 371, name: "Cañas", canton_id: 60 },
  { id: 372, name: "Palmira", canton_id: 60 },
  { id: 373, name: "San Miguel", canton_id: 60 },
  { id: 374, name: "Bebedero", canton_id: 60 },
  { id: 375, name: "Porozal", canton_id: 60 },
  // Abangares (61)
  { id: 376, name: "Las Juntas", canton_id: 61 },
  { id: 377, name: "Sierra", canton_id: 61 },
  { id: 378, name: "San Juan", canton_id: 61 },
  { id: 379, name: "Colorado", canton_id: 61 },
  // Tilarán (62)
  { id: 380, name: "Tilarán", canton_id: 62 },
  { id: 381, name: "Quebrada Grande", canton_id: 62 },
  { id: 382, name: "San Pedro", canton_id: 62 },
  { id: 383, name: "Blanco", canton_id: 62 },
  { id: 384, name: "Liberia", canton_id: 62 },
  { id: 385, name: "Tierras Morenas", canton_id: 62 },
  { id: 386, name: "Arenal", canton_id: 62 },
  { id: 387, name: "Cabeceras", canton_id: 62 },
  // Nandayure (63)
  { id: 388, name: "Carmona", canton_id: 63 },
  { id: 389, name: "Santa Rita", canton_id: 63 },
  { id: 390, name: "Zapotal", canton_id: 63 },
  { id: 391, name: "San Pablo", canton_id: 63 },
  { id: 392, name: "Porvenir", canton_id: 63 },
  { id: 393, name: "Bejuco", canton_id: 63 },
  // La Cruz (64)
  { id: 394, name: "La Cruz", canton_id: 64 },
  { id: 395, name: "Santa Cecilia", canton_id: 64 },
  { id: 396, name: "La Garita", canton_id: 64 },
  { id: 397, name: "Santa Elena", canton_id: 64 },
  // Hojancha (65)
  { id: 398, name: "Hojancha", canton_id: 65 },
  { id: 399, name: "Monte Romo", canton_id: 65 },
  { id: 400, name: "Puerto Carrillo", canton_id: 65 },
  { id: 401, name: "Huacas", canton_id: 65 },
  { id: 402, name: "Matambú", canton_id: 65 },
  // Puntarenas (66)
  { id: 403, name: "Puntarenas", canton_id: 66 },
  { id: 404, name: "Pitahaya", canton_id: 66 },
  { id: 405, name: "Chomes", canton_id: 66 },
  { id: 406, name: "Lepanto", canton_id: 66 },
  { id: 407, name: "Paquera", canton_id: 66 },
  { id: 408, name: "Manzanillo", canton_id: 66 },
  { id: 409, name: "Guacimal", canton_id: 66 },
  { id: 410, name: "Barranca", canton_id: 66 },
  { id: 411, name: "Monte Verde", canton_id: 66 },
  { id: 412, name: "Isla del Coco", canton_id: 66 },
  { id: 413, name: "Cóbano", canton_id: 66 },
  { id: 414, name: "Chacarita", canton_id: 66 },
  { id: 415, name: "Chira", canton_id: 66 },
  { id: 416, name: "Acapulco", canton_id: 66 },
  { id: 417, name: "El Roble", canton_id: 66 },
  { id: 418, name: "Arancibia", canton_id: 66 },
  // Esparza (67)
  { id: 419, name: "Espíritu Santo", canton_id: 67 },
  { id: 420, name: "San Juan Grande", canton_id: 67 },
  { id: 421, name: "Macacona", canton_id: 67 },
  { id: 422, name: "San Rafael", canton_id: 67 },
  { id: 423, name: "San Jerónimo", canton_id: 67 },
  { id: 424, name: "Caldera", canton_id: 67 },
  // Buenos Aires (68)
  { id: 425, name: "Buenos Aires", canton_id: 68 },
  { id: 426, name: "Volcán", canton_id: 68 },
  { id: 427, name: "Potrero Grande", canton_id: 68 },
  { id: 428, name: "Boruca", canton_id: 68 },
  { id: 429, name: "Pilas", canton_id: 68 },
  { id: 430, name: "Colinas", canton_id: 68 },
  { id: 431, name: "Chánguena", canton_id: 68 },
  { id: 432, name: "Biolley", canton_id: 68 },
  { id: 433, name: "Brunka", canton_id: 68 },
  // Montes de Oro (69)
  { id: 434, name: "Miramar", canton_id: 69 },
  { id: 435, name: "La Unión", canton_id: 69 },
  { id: 436, name: "San Isidro", canton_id: 69 },
  // Osa (70)
  { id: 437, name: "Puerto Cortés", canton_id: 70 },
  { id: 438, name: "Palmar", canton_id: 70 },
  { id: 439, name: "Sierpe", canton_id: 70 },
  { id: 440, name: "Bahía Ballena", canton_id: 70 },
  { id: 441, name: "Piedras Blancas", canton_id: 70 },
  { id: 442, name: "Bahía Drake", canton_id: 70 },
  // Quepos (71)
  { id: 443, name: "Quepos", canton_id: 71 },
  { id: 444, name: "Savegre", canton_id: 71 },
  { id: 445, name: "Naranjito", canton_id: 71 },
  // Golfito (72)
  { id: 446, name: "Golfito", canton_id: 72 },
  { id: 447, name: "Puerto Jiménez", canton_id: 72 },
  { id: 448, name: "Guaycará", canton_id: 72 },
  { id: 449, name: "Pavón", canton_id: 72 },
  // Coto Brus (73)
  { id: 450, name: "San Vito", canton_id: 73 },
  { id: 451, name: "Sabalito", canton_id: 73 },
  { id: 452, name: "Aguabuena", canton_id: 73 },
  { id: 453, name: "Limoncito", canton_id: 73 },
  { id: 454, name: "Pittier", canton_id: 73 },
  { id: 455, name: "Gutiérrez Braun", canton_id: 73 },
  // Parrita (74)
  { id: 456, name: "Parrita", canton_id: 74 },
  // Corredores (75)
  { id: 457, name: "Corredor", canton_id: 75 },
  { id: 458, name: "La Cuesta", canton_id: 75 },
  { id: 459, name: "Canoas", canton_id: 75 },
  { id: 460, name: "Laurel", canton_id: 75 },
  // Garabito (76)
  { id: 461, name: "Jacó", canton_id: 76 },
  { id: 462, name: "Tárcoles", canton_id: 76 },
  { id: 463, name: "Lagunillas", canton_id: 76 },
  // Limón (77)
  { id: 464, name: "Limón", canton_id: 77 },
  { id: 465, name: "Valle La Estrella", canton_id: 77 },
  { id: 466, name: "Río Blanco", canton_id: 77 },
  { id: 467, name: "Matama", canton_id: 77 },
  // Pococí (78)
  { id: 468, name: "Guápiles", canton_id: 78 },
  { id: 469, name: "Jiménez", canton_id: 78 },
  { id: 470, name: "La Rita", canton_id: 78 },
  { id: 471, name: "Roxana", canton_id: 78 },
  { id: 472, name: "Cariari", canton_id: 78 },
  { id: 473, name: "Colorado", canton_id: 78 },
  { id: 474, name: "La Colonia", canton_id: 78 },
  // Siquirres (79)
  { id: 475, name: "Siquirres", canton_id: 79 },
  { id: 476, name: "Pacuarito", canton_id: 79 },
  { id: 477, name: "Florida", canton_id: 79 },
  { id: 478, name: "Germania", canton_id: 79 },
  { id: 479, name: "El Cairo", canton_id: 79 },
  { id: 480, name: "Alegría", canton_id: 79 },
  { id: 481, name: "Reventazón", canton_id: 79 },
  // Talamanca (80)
  { id: 482, name: "Bratsi", canton_id: 80 },
  { id: 483, name: "Sixaola", canton_id: 80 },
  { id: 484, name: "Cahuita", canton_id: 80 },
  { id: 485, name: "Telire", canton_id: 80 },
  // Matina (81)
  { id: 486, name: "Matina", canton_id: 81 },
  { id: 487, name: "Batán", canton_id: 81 },
  { id: 488, name: "Carrandi", canton_id: 81 },
  // Guácimo (82)
  { id: 489, name: "Guácimo", canton_id: 82 },
  { id: 490, name: "Mercedes", canton_id: 82 },
  { id: 491, name: "Pocora", canton_id: 82 },
  { id: 492, name: "Río Jiménez", canton_id: 82 },
  { id: 493, name: "Duacarí", canton_id: 82 },
];

export const getCantonsByProvince = (provinceId: number): Canton[] => {
  return cantons.filter((c) => c.province_id === provinceId);
};

export const getDistrictsByCanton = (cantonId: number): District[] => {
  return districts.filter((d) => d.canton_id === cantonId);
};
